version: "3.5"
services:
  express-backend:
    image: pinaruss/temporal-demo-backend
    networks:
      - backend-network
    ports:
      - "9099:9099"
    labels:
      kompose.service.type: loadbalancer
networks:
  backend-network:
    driver: bridge
    name: backend-network
