version: "3.5"
services:
  onboard-worker:
    image: pinaruss/onboard-worker
    networks:
      - temporal-worker-network
    labels:
      kompose.service.type: headless
networks:
  temporal-worker-network:
    driver: bridge
    name: temporal-worker-network