version: "3.5"

services:
  onboard-worker:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start.onworker